name: Deploy

on:
  push:
    branches:
      - main # Change this to your default branch if different (e.g. "trunk", or "master")

env:
  SANITY_STUDIO_PROJECT_ID: ${{ vars.SANITY_STUDIO_PROJECT_ID }}
  SANITY_STUDIO_DATASET: ${{ vars.SANITY_STUDIO_DATASET }}

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the website
        run: pnpm run web:build

      - name: Install s3cmd
        run: sudo apt-get install -y s3cmd

      - name: Install the Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          version: v2.37.0

      - run: |
          scw object config get type=s3cmd > /home/runner/.s3cfg
          s3cmd --no-mime-magic --guess-mime-type sync ./packages/web/dist/* s3://bram-is/
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
